# Generated by Django 5.1 on 2024-10-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0002_alter_notification_options_notification_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='form',
        ),
    ]
