# Generated by Django 5.1 on 2024-10-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0003_remove_notification_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='obj_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='ссылка на объект'),
        ),
    ]
