# Generated by Django 5.1 on 2024-12-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0004_notification_obj_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='описание уведомления'),
        ),
    ]
