# Generated by Django 5.1 on 2024-08-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_user_city_alter_user_email_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.PositiveIntegerField(default=0, verbose_name='баллы'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='level',
            field=models.CharField(max_length=255, verbose_name='рейтинг'),
        ),
    ]
