# Generated by Django 5.1 on 2024-08-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_rating_options_alter_user_options'),
        ('user_app', '0004_user_point_alter_rating_level'),
    ]

    operations = [
    ]
