# Generated by Django 5.1 on 2024-09-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_merge_20240827_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent_to_personal_data',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='18+'),
        ),
    ]
