# Generated by Django 5.1 on 2024-09-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_merge_20240827_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='hours_needed',
            field=models.PositiveIntegerField(default=0, verbose_name='часы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='куратор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='сотрудник'),
        ),
    ]
