# Generated by Django 5.1 on 2024-09-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_user_consent_to_personal_data_user_is_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.PositiveBigIntegerField(db_index=True, unique=True, verbose_name='телеграм ID'),
        ),
    ]
