# Generated by Django 5.1 on 2024-09-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_rating_hours_needed_alter_user_is_staff_and_more'),
        ('user_app', '0007_alter_user_tg_id'),
    ]

    operations = [
    ]
