# Generated by Django 5.1 on 2024-09-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_merge_20240916_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_adult',
            field=models.BooleanField(default=True, verbose_name='18+'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Сотрудник'),
        ),
    ]
