# Generated by Django 5.1 on 2024-10-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_user_avatar_user_birthday_user_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='никнэйм'),
        ),
    ]
