# Generated by Django 5.1 on 2024-10-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_alter_user_tg_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='consent_to_personal_data',
            field=models.BooleanField(default=False, help_text='Согласие на обработку персональных данных', verbose_name='Согласие'),
        ),
    ]
