# Generated by Django 5.1 on 2024-10-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_alter_user_consent_to_personal_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='consent_to_personal_data',
            field=models.BooleanField(default=False, help_text='Принятие условий договора-оферты', verbose_name='Согласие'),
        ),
    ]
