# Generated by Django 5.1 on 2024-10-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_curator_employee_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='photo_view',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='фотография пользователя'),
        ),
    ]
