# Generated by Django 5.1 on 2024-10-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_remove_user_avatar_user_photo_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='volunteer_hour',
            field=models.PositiveIntegerField(default=0, verbose_name='волонтерские часы'),
        ),
    ]
