# Generated by Django 5.1 on 2024-11-17 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0026_alter_address_location_alter_address_route_sheet_and_more'),
        ('user_app', '0018_user_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='address_app.city', verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.rating', verbose_name='рейтинг'),
        ),
    ]
