# Generated by Django 5.1 on 2024-12-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_alter_user_is_confirmed_alter_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.PositiveBigIntegerField(db_index=True, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ник'),
        ),
        migrations.AlterField(
            model_name='user',
            name='volunteer_hour',
            field=models.PositiveIntegerField(default=0, verbose_name='часы'),
        ),
    ]
