# Generated by Django 5.1 on 2024-08-20 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField()),
                ('file', models.FileField(upload_to='promotion/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_app.city')),
            ],
        ),
    ]
