# Generated by Django 5.1 on 2024-08-21 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0004_alter_address_address_alter_address_link_and_more'),
        ('promo_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='category',
            field=models.CharField(max_length=255, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address_app.city', verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='date',
            field=models.DateTimeField(verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='promotion/', verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активная'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='price',
            field=models.PositiveIntegerField(verbose_name='стоимость'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='получатель'),
        ),
    ]
