# Generated by Django 5.1 on 2024-08-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0004_alter_promotion_options'),
        ('promo_app', '0004_promotion_for_curators_only'),
    ]

    operations = [
    ]
