# Generated by Django 5.1 on 2024-09-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0005_merge_20240827_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'поощрение', 'verbose_name_plural': 'поощрения'},
        ),
    ]
