# Generated by Django 5.1 on 2024-09-12 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0006_alter_promotion_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='user',
        ),
        migrations.AddField(
            model_name='promotion',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='срок действия'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_permanent',
            field=models.BooleanField(default=False, verbose_name='бессрочное поощрение'),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='дата получения')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo_app.promotion', verbose_name='поощрение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='волонтёр')),
            ],
            options={
                'verbose_name': 'участие',
                'verbose_name_plural': 'участия',
            },
        ),
        migrations.AddField(
            model_name='promotion',
            name='users',
            field=models.ManyToManyField(blank=True, through='promo_app.Participation', to=settings.AUTH_USER_MODEL, verbose_name='получатель'),
        ),
    ]
