# Generated by Django 5.1 on 2024-09-16 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0007_remove_promotion_user_promotion_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='expiry_date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='date',
        ),
        migrations.AddField(
            model_name='promotion',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='доступное количество'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начала поощрения'),
        ),
    ]
