# Generated by Django 5.1 on 2024-09-17 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0009_promocategory_promotion_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promo_app.promocategory', verbose_name='категория'),
        ),
    ]
