# Generated by Django 5.1 on 2024-09-17 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0016_routesheet_location_alter_routesheet_user'),
        ('promo_app', '0010_alter_promotion_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address_app.city', verbose_name='город'),
            preserve_default=False,
        ),
    ]
