# Generated by Django 5.1 on 2024-10-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0011_alter_promotion_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'участники', 'verbose_name_plural': 'участники'},
        ),
    ]
