# Generated by Django 5.1 on 2024-10-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0012_alter_participation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='адрес'),
        ),
    ]
