# Generated by Django 5.1 on 2024-10-12 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0013_promotion_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='file',
            new_name='ticket_file',
        ),
        migrations.AddField(
            model_name='promotion',
            name='about_tickets',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='информация о билетах'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Изначально должно быть равно количеству. Будет меняться автоматически', verbose_name='доступное количество'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Только если поощрение не бессрочное', null=True, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='picture',
            field=models.ImageField(blank=True, help_text='Ширина 328px, высота 205px', null=True, upload_to='', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Общее количество'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начала'),
        ),
    ]
