# Generated by Django 5.1 on 2024-10-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0014_rename_file_promotion_ticket_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='подтверждение'),
        ),
    ]
