# Generated by Django 5.1 on 2024-11-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0016_promotion_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='picture',
            field=models.ImageField(blank=True, help_text='Ширина 328px, высота 205px', null=True, upload_to='promo_pictures/', verbose_name='картинка'),
        ),
    ]
