# Generated by Django 5.1 on 2024-11-17 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0026_alter_address_location_alter_address_route_sheet_and_more'),
        ('promo_app', '0017_alter_promotion_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo_app.promocategory', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address_app.city', verbose_name='город'),
        ),
    ]
