# Generated by Django 5.1 on 2025-03-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0019_alter_promotion_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='about_tickets',
            field=models.TextField(blank=True, null=True, verbose_name='информация о билетах'),
        ),
    ]
