# Generated by Django 5.1 on 2024-11-06 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField(verbose_name='Номер недели')),
                ('month', models.PositiveIntegerField(default=11, verbose_name='Месяц')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('hours', models.PositiveIntegerField(default=0, verbose_name='Часы')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Баллы')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер')),
            ],
            options={
                'verbose_name': 'Статистика волонтера',
                'verbose_name_plural': 'Статистика волонтеров',
                'unique_together': {('volunteer', 'week', 'year')},
            },
        ),
    ]
