# Generated by Django 5.1 on 2024-12-23 07:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0003_alter_volunteerstats_month_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Баллы')),
                ('volunteer_hours', models.PositiveIntegerField(default=0, verbose_name='Часы')),
                ('period', models.DateField(default=django.utils.timezone.now, verbose_name='Период')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер')),
            ],
            options={
                'verbose_name': 'Статистика волонтера',
                'verbose_name_plural': 'Статистика волонтеров',
                'unique_together': {('volunteer', 'period')},
            },
        ),
    ]
