# Generated by Django 5.1 on 2024-12-23 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0004_statistics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsByMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Баллы в месяц')),
                ('hours', models.PositiveIntegerField(default=0, verbose_name='Часы в месяц')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stats_by_month', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер')),
            ],
            options={
                'verbose_name': 'Статистика волонтера по месяцам',
                'verbose_name_plural': 'Статистика волонтеров по месяцам',
                'unique_together': {('user', 'points', 'hours')},
            },
        ),
        migrations.CreateModel(
            name='StatisticsByWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Баллы в неделю')),
                ('hours', models.PositiveIntegerField(default=0, verbose_name='Часы в неделю')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stats_by_week', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер')),
            ],
            options={
                'verbose_name': 'Статистика волонтера по неделям',
                'verbose_name_plural': 'Статистика волонтеров по неделям',
                'unique_together': {('user', 'points', 'hours')},
            },
        ),
        migrations.CreateModel(
            name='StatisticsByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Баллы в год')),
                ('hours', models.PositiveIntegerField(default=0, verbose_name='Часы в год')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stats_by_year', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер')),
            ],
            options={
                'verbose_name': 'Статистика волонтера по годам',
                'verbose_name_plural': 'Статистика волонтеров по годам',
                'unique_together': {('user', 'points', 'hours')},
            },
        ),
        migrations.DeleteModel(
            name='VolunteerStats',
        ),
    ]
