# Generated by Django 5.1 on 2024-12-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0005_statisticsbymonth_statisticsbyweek_statisticsbyyear_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_week', models.PositiveIntegerField(default=0, verbose_name='Всего баллов потраченных за неделю')),
                ('hours_week', models.PositiveIntegerField(default=0, verbose_name='Заработанные часы за неделю')),
                ('points_month', models.PositiveIntegerField(default=0, verbose_name='Всего баллов потраченных за месяц')),
                ('hours_month', models.PositiveIntegerField(default=0, verbose_name='Заработанные часы за месяц')),
                ('points_year', models.PositiveIntegerField(default=0, verbose_name='Всего баллов потраченных за год')),
                ('hours_year', models.PositiveIntegerField(default=0, verbose_name='Заработанные часы за год')),
            ],
            options={
                'verbose_name': 'Общая статистика',
                'verbose_name_plural': 'Общая статистика',
            },
        ),
        migrations.AlterField(
            model_name='statisticsbymonth',
            name='hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Заработанные часы за месяц'),
        ),
        migrations.AlterField(
            model_name='statisticsbymonth',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы потраченные за месяц'),
        ),
        migrations.AlterField(
            model_name='statisticsbyweek',
            name='hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Заработанные часы за неделю'),
        ),
        migrations.AlterField(
            model_name='statisticsbyweek',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы потраченные за неделю'),
        ),
        migrations.AlterField(
            model_name='statisticsbyyear',
            name='hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Заработанные часы за год'),
        ),
        migrations.AlterField(
            model_name='statisticsbyyear',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы потраченные за год'),
        ),
    ]
