# Generated by Django 5.1 on 2025-02-11 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0006_allstatistics_alter_statisticsbymonth_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsbymonth',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_by_month', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер'),
        ),
        migrations.AlterField(
            model_name='statisticsbyweek',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_by_week', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер'),
        ),
        migrations.AlterField(
            model_name='statisticsbyyear',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_by_year', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер'),
        ),
        migrations.AlterUniqueTogether(
            name='allstatistics',
            unique_together={('points_week', 'hours_week', 'points_month', 'hours_month', 'points_year', 'hours_year')},
        ),
    ]
