# Generated by Django 5.1 on 2025-03-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0007_alter_statisticsbymonth_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllStatistics',
        ),
        migrations.AlterUniqueTogether(
            name='statisticsbymonth',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='statisticsbymonth',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='statisticsbyweek',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='statisticsbyweek',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='statisticsbyyear',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='statisticsbyyear',
            name='user',
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
        migrations.DeleteModel(
            name='StatisticsByMonth',
        ),
        migrations.DeleteModel(
            name='StatisticsByWeek',
        ),
        migrations.DeleteModel(
            name='StatisticsByYear',
        ),
    ]
