# Generated by Django 5.1 on 2024-09-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=255, unique=True, verbose_name='имя для ссылки')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='stories_cover', verbose_name='обложка')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='текст')),
                ('media_files', models.FileField(blank=True, null=True, upload_to='stories_files', verbose_name='файлы')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='ссылка')),
                ('hidden', models.BooleanField(default=False, verbose_name='скрыт')),
            ],
            options={
                'verbose_name': 'сторис',
                'verbose_name_plural': 'сторисы',
            },
        ),
    ]
