# Generated by Django 5.1 on 2024-09-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories_app', '0002_remove_stories_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='фон'),
        ),
    ]
