# Generated by Django 5.1 on 2024-10-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories_app', '0003_stories_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='cover',
            field=models.ImageField(blank=True, help_text='Обложка для сториса в приложении. Ширина 116, высота 160 пикселей, формат SVG, PNG', null=True, upload_to='stories_cover', verbose_name='обложка'),
        ),
    ]
