# Generated by Django 5.1 on 2024-10-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories_app', '0004_alter_stories_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='link_name',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='media_files',
        ),
        migrations.AddField(
            model_name='stories',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='дата'),
        ),
        migrations.AddField(
            model_name='stories',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='подзаголовок'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='background',
            field=models.ImageField(blank=True, help_text='Фон для сториса в приложении. Ширина 360, высота 634 пикселей, формат SVG, PNG, JPG', null=True, upload_to='stories_background', verbose_name='фон'),
        ),
    ]
