# Generated by Django 5.1 on 2024-12-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories_app', '0006_alter_stories_text_alter_stories_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='cover',
            field=models.ImageField(default=1, help_text='Обложка для сториса в приложении. Ширина 116, высота 160 пикселей, формат SVG, PNG', upload_to='stories_cover', verbose_name='обложка'),
            preserve_default=False,
        ),
    ]
