# Generated by Django 5.1 on 2024-08-21 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0003_alter_address_route_sheet'),
        ('task_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(verbose_name='дата доставки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активная'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='свободная'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='price',
            field=models.PositiveIntegerField(verbose_name='часы'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='route_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_app.routesheet', verbose_name='маршрутный лист'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='volunteer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='волонтёр'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(max_length=255, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='task',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address_app.city', verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='task',
            name='curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_curator', to=settings.AUTH_USER_MODEL, verbose_name='куратор'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='длительность'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активная'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.PositiveIntegerField(verbose_name='часы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='количество волонтёров'),
        ),
        migrations.AlterField(
            model_name='task',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_volunteer', to=settings.AUTH_USER_MODEL, verbose_name='волонтёр'),
        ),
    ]
