# Generated by Django 5.1 on 2024-08-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_delivery_date_alter_delivery_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateTimeField(verbose_name='дата доставки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(verbose_name='дата'),
        ),
    ]
