# Generated by Django 5.1 on 2024-08-23 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0005_location_subway'),
        ('task_app', '0005_alter_task_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='route_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='address_app.routesheet', verbose_name='маршрутный лист'),
        ),
    ]
