# Generated by Django 5.1 on 2024-08-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_alter_task_volunteer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'доставка', 'verbose_name_plural': 'доставки'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'задание', 'verbose_name_plural': 'задания'},
        ),
    ]
