# Generated by Django 5.1 on 2024-08-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0006_alter_delivery_options_alter_task_options'),
        ('task_app', '0006_alter_delivery_route_sheet'),
    ]

    operations = [
    ]
