# Generated by Django 5.1 on 2024-08-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_alter_task_end_date_alter_task_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='quantity',
        ),
        migrations.AddField(
            model_name='task',
            name='volunteers_needed',
            field=models.PositiveIntegerField(default=2, verbose_name='требуется волонтеров'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='volunteers_taken',
            field=models.PositiveIntegerField(default=0, verbose_name='волонтеров взяли'),
        ),
    ]
