# Generated by Django 5.1 on 2024-08-27 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0010_remove_task_quantity_task_volunteers_needed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='task',
            name='volunteer',
            field=models.ManyToManyField(blank=True, related_name='task_volunteer', to=settings.AUTH_USER_MODEL, verbose_name='волонтер'),
        ),
    ]
