# Generated by Django 5.1 on 2024-08-27 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0011_remove_task_volunteer_task_volunteer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='task',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='task_volunteers', to=settings.AUTH_USER_MODEL, verbose_name='волонтёры'),
        ),
    ]
