# Generated by Django 5.1 on 2024-09-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0008_alter_delivery_options_delivery_in_execution_and_more'),
        ('task_app', '0014_task_is_completed'),
    ]

    operations = [
    ]
