# Generated by Django 5.1 on 2024-09-10 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0013_routesheet_user'),
        ('task_app', '0015_merge_20240909_1214'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'доставка', 'verbose_name_plural': 'доставки'},
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='delivery',
            name='volunteers_needed',
            field=models.PositiveIntegerField(default=1, verbose_name='требуется волонтёров'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='volunteers_taken',
            field=models.PositiveIntegerField(default=0, verbose_name='волонтёров взяли'),
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='route_sheet',
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='task_app.delivery', verbose_name='доставка')),
                ('volunteer', models.ManyToManyField(related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='волонтёр')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='route_sheet',
            field=models.ManyToManyField(related_name='delivery', to='address_app.routesheet', verbose_name='маршрутный лист'),
        ),
    ]
