# Generated by Django 5.1 on 2024-09-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0015_merge_20240909_1505'),
        ('task_app', '0016_alter_delivery_options_remove_delivery_volunteer_and_more'),
    ]

    operations = [
    ]
