# Generated by Django 5.1 on 2024-09-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0019_delivery_curator'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория задания',
                'verbose_name_plural': 'категории заданий',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='категория'),
        ),
    ]
