# Generated by Django 5.1 on 2024-09-15 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0016_routesheet_location_alter_routesheet_user'),
        ('task_app', '0019_delivery_curator'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_route', to='task_app.delivery', verbose_name='доставка')),
                ('route_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_route', to='address_app.routesheet', verbose_name='маршрутный лист')),
            ],
            options={
                'verbose_name': 'маршрутный лист для доставки',
                'verbose_name_plural': 'маршрутные листы для доставок',
            },
        ),
        migrations.AlterField(
            model_name='delivery',
            name='route_sheet',
            field=models.ManyToManyField(related_name='delivery', through='task_app.DeliveryRoute', to='address_app.routesheet', verbose_name='маршрутный лист'),
        ),
    ]
