# Generated by Django 5.1 on 2024-09-18 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0016_routesheet_location_alter_routesheet_user'),
        ('task_app', '0020_taskcategory_alter_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='address_app.location', verbose_name='Локация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.taskcategory', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='task',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address_app.city', verbose_name='город'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='volunteers_needed',
            field=models.PositiveIntegerField(default=1, verbose_name='требуется волонтёров'),
        ),
    ]
