# Generated by Django 5.1 on 2024-10-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0021_delivery_location_alter_task_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'доставка', 'verbose_name_plural': 'доставки'},
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='task_category_icons/', verbose_name='иконка'),
        ),
    ]
