# Generated by Django 5.1 on 2024-10-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0022_alter_delivery_options_taskcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.PositiveIntegerField(default=2, verbose_name='часы'),
        ),
    ]
