# Generated by Django 5.1 on 2024-10-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0023_alter_task_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='price',
            field=models.PositiveIntegerField(default=2, verbose_name='часы'),
        ),
    ]
