# Generated by Django 5.1 on 2024-10-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0024_alter_delivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='icon',
            field=models.ImageField(blank=True, help_text='размер 32x32 пикселей, форматы SVG, PNG', null=True, upload_to='task_category_icons/', verbose_name='иконка'),
        ),
    ]
