# Generated by Django 5.1 on 2024-10-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0025_alter_taskcategory_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'доброе дело', 'verbose_name_plural': 'добрые дела'},
        ),
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'verbose_name': 'категория добрых дел', 'verbose_name_plural': 'категории добрых дел'},
        ),
    ]
