# Generated by Django 5.1 on 2024-11-17 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0026_alter_address_location_alter_address_route_sheet_and_more'),
        ('task_app', '0027_alter_deliveryassignment_options_remove_task_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to=settings.AUTH_USER_MODEL, verbose_name='куратор'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='address_app.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_app.taskcategory', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='task',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address_app.city', verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='task',
            name='curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_curator', to=settings.AUTH_USER_MODEL, verbose_name='куратор'),
        ),
    ]
