# Generated by Django 5.1 on 2024-12-12 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0030_alter_deliveryassignment_volunteer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryassignment',
            name='volunteer',
            field=models.ManyToManyField(related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='волонтёр'),
        ),
    ]
