# Generated by Django 5.1 on 2025-01-13 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0031_alter_deliveryassignment_volunteer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_curator', to=settings.AUTH_USER_MODEL, verbose_name='ответственный'),
        ),
    ]
