# Generated by Django 5.1 on 2025-03-03 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0031_merge_20250302_2010'),
        ('task_app', '0032_alter_task_curator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='подтвержд.'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='in_execution',
            field=models.BooleanField(default=False, verbose_name='выпол.'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='актив.'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='завер.'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='своб.'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='route_sheet',
            field=models.ManyToManyField(related_name='delivery', to='address_app.routesheet', verbose_name='маршрут'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='volunteers_needed',
            field=models.PositiveIntegerField(default=1, verbose_name='нужно'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='volunteers_taken',
            field=models.PositiveIntegerField(default=0, verbose_name='взяли'),
        ),
        migrations.CreateModel(
            name='TaskParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False, verbose_name='подтверждено')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_part', to='task_app.task', verbose_name='задача')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_part', to=settings.AUTH_USER_MODEL, verbose_name='волонтёр')),
            ],
        ),
    ]
