# Generated by Django 5.1 on 2025-03-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0033_alter_delivery_in_execution_alter_delivery_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='подтвержд.'),
        ),
    ]
