# Generated by Django 5.1 on 2025-03-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0033_deliveryassignment_confirm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskparticipation',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='завершено'),
        ),
    ]
