# Generated by Django 5.1 on 2025-03-03 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0034_deliveryassignment_confirm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False, verbose_name='подтверждено')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_part', to='task_app.task', verbose_name='задача')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_part', to=settings.AUTH_USER_MODEL, verbose_name='волонтёр')),
            ],
        ),
    ]
