# Generated by Django 5.1 on 2025-03-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0034_taskparticipation_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_one_day',
            field=models.BooleanField(default=True, verbose_name='Однодневная задача'),
        ),
        migrations.AlterField(
            model_name='taskparticipation',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='завершить'),
        ),
    ]
