# Generated by Django 5.1 on 2025-03-20 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0035_task_is_one_day_alter_taskparticipation_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 0, 0), verbose_name='дата конца'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 0, 0), verbose_name='дата начала'),
        ),
    ]
