# Generated by Django 5.1 on 2024-10-08 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address_app', '0019_remove_location_codename'),
        ('promo_app', '0013_promotion_address'),
        ('task_app', '0026_alter_task_options_alter_taskcategory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('delivery', 'Доставка'), ('promotion', 'Поощрение')], max_length=20, verbose_name='Тип обратной связи')),
                ('text', models.TextField(verbose_name='Текст обратной связи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='task_app.delivery', verbose_name='Доставка')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='promo_app.promotion', verbose_name='Поощрение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'обратная связь',
                'verbose_name_plural': 'обратная связь',
            },
        ),
        migrations.CreateModel(
            name='PhotoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(blank=True, max_length=500, null=True, verbose_name='фото')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_app.address', verbose_name='адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='RequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='тип заявки')),
                ('text', models.TextField(blank=True, null=True, verbose_name='текст')),
                ('form', models.URLField(blank=True, max_length=500, null=True, verbose_name='форма')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
            },
        ),
    ]
