# Generated by Django 5.1 on 2024-10-11 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
        ('task_app', '0026_alter_task_options_alter_taskcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='task_app.task', verbose_name='Доброе дело'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('completed_delivery', 'Завершенная доставка'), ('canceled_delivery', 'Отмененная доставка'), ('completed_promotion', 'Завершенное поощрение'), ('canceled_promotion', 'Отмененное поощрение'), ('completed_task', 'Завершенное доброе дело'), ('canceled_task', 'Отмененное доброе дело')], max_length=20, verbose_name='Тип обратной связи'),
        ),
    ]
