# Generated by Django 5.1 on 2024-09-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestmessage',
            options={'verbose_name': 'заявка', 'verbose_name_plural': 'заявки'},
        ),
        migrations.AlterField(
            model_name='requestmessage',
            name='type',
            field=models.CharField(max_length=255, verbose_name='тип заявки'),
        ),
    ]
