# Generated by Django 5.1 on 2024-10-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmessage',
            name='form',
        ),
    ]
