# Generated by Django 5.1 on 2024-08-21 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='form',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='форма'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(max_length=255, verbose_name='тип отзыва'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='request',
            name='form',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='форма'),
        ),
        migrations.AlterField(
            model_name='request',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(max_length=255, verbose_name='тип запроса'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
