# Generated by Django 5.1 on 2024-10-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_feedback_task_alter_feedback_type'),
        ('feedback_app', '0002_remove_requestmessage_form'),
    ]

    operations = [
    ]
