# Generated by Django 5.1 on 2024-09-20 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0016_routesheet_location_alter_routesheet_user'),
        ('feedback_app', '0002_alter_requestmessage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(blank=True, max_length=500, null=True, verbose_name='фото')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_app.address', verbose_name='адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
