# Generated by Django 5.1 on 2024-08-23 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0003_alter_feedback_form_alter_feedback_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='RequestMessage',
        ),
    ]
