# Generated by Django 5.1 on 2024-08-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0003_alter_feedback_form_alter_feedback_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'запрос', 'verbose_name_plural': 'запросы'},
        ),
    ]
