# Generated by Django 5.1 on 2024-10-02 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0003_photoreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmessage',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата'),
            preserve_default=False,
        ),
    ]
