# Generated by Django 5.1 on 2024-10-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0004_remove_photoreport_photo_photoreport_photo_download_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('completed_delivery', 'Завершенная доставка'), ('canceled_delivery', 'Отмененная доставка'), ('completed_promotion', 'Завершенное поощрение'), ('canceled_promotion', 'Отмененное поощрение'), ('completed_task', 'Завершенное доброе дело'), ('canceled_task', 'Отмененное доброе дело'), ('suggestion', 'Вопросы и предложения')], max_length=20, verbose_name='Тип обратной связи'),
        ),
    ]
