# Generated by Django 5.1 on 2024-10-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0005_remove_feedback_form_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'обратная связь', 'verbose_name_plural': 'обратная связь'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(verbose_name='Текст обратной связи'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('promotion', 'Поощрение')], max_length=20, verbose_name='Тип обратной связи'),
        ),
    ]
