# Generated by Django 5.1 on 2024-10-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0005_remove_requestmessage_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Текст обратной связи'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='комментарий'),
        ),
    ]
