# Generated by Django 5.1 on 2024-10-14 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0005_alter_feedback_type'),
        ('feedback_app', '0007_requestmessage_type'),
    ]

    operations = [
    ]
