# Generated by Django 5.1 on 2024-11-17 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0026_alter_address_location_alter_address_route_sheet_and_more'),
        ('feedback_app', '0008_merge_20241014_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoreport',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address_app.address', verbose_name='адрес'),
        ),
    ]
