# Generated by Django 5.1 on 2024-11-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0009_alter_photoreport_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoreport',
            name='photo_download',
        ),
    ]
