# Generated by Django 5.1 on 2024-11-27 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0026_alter_address_location_alter_address_route_sheet_and_more'),
        ('feedback_app', '0010_remove_photoreport_photo_download'),
        ('task_app', '0028_alter_delivery_curator_alter_delivery_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photoreport',
            name='delivery_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_app.delivery', verbose_name='доставка'),
        ),
        migrations.AddField(
            model_name='photoreport',
            name='photo_download',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='', verbose_name='загрузка фотографии'),
        ),
        migrations.AddField(
            model_name='photoreport',
            name='route_sheet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address_app.routesheet', verbose_name='маршрутный лист'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
