# Generated by Django 5.1 on 2024-12-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0012_alter_feedback_delivery_alter_feedback_promotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('completed_delivery', 'Завершенная доставка'), ('canceled_delivery', 'Отмененная доставка'), ('completed_promotion', 'Завершенное поощрение'), ('canceled_promotion', 'Отмененное поощрение'), ('completed_task', 'Завершенное доброе дело'), ('canceled_task', 'Отмененное доброе дело'), ('suggestion', 'Вопросы и предложения'), ('support', 'Техническая поддержка')], max_length=20, verbose_name='Тип обратной связи'),
        ),
    ]
