# Generated by Django 5.1 on 2025-01-10 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0027_alter_location_curator'),
        ('feedback_app', '0015_alter_feedback_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoreport',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address_app.address', verbose_name='адрес'),
        ),
    ]
