# Generated by Django 5.1 on 2024-08-21 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='route_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_route_sheet', to='address_app.routesheet'),
        ),
    ]
