# Generated by Django 5.1 on 2024-08-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0004_alter_address_address_alter_address_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'адрес', 'verbose_name_plural': 'адреса'},
        ),
        migrations.AlterModelOptions(
            name='beneficiar',
            options={'verbose_name': 'благо получатель', 'verbose_name_plural': 'благо получатели'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'город', 'verbose_name_plural': 'города'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'локация', 'verbose_name_plural': 'локации'},
        ),
        migrations.AlterModelOptions(
            name='routesheet',
            options={'verbose_name': 'маршрутный лист', 'verbose_name_plural': 'маршрутные листы'},
        ),
    ]
