# Generated by Django 5.1 on 2024-08-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0005_alter_address_options_alter_beneficiar_options_and_more'),
        ('address_app', '0005_location_subway'),
    ]

    operations = [
    ]
