# Generated by Django 5.1 on 2024-08-30 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0006_merge_20240827_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiar',
            options={'verbose_name': 'благополучатель', 'verbose_name_plural': 'благополучатели'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='route_sheet',
        ),
        migrations.CreateModel(
            name='RoureAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_app.address', verbose_name='адрес')),
                ('route_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_app.routesheet', verbose_name='маршрутный лист')),
            ],
        ),
        migrations.AddField(
            model_name='routesheet',
            name='address',
            field=models.ManyToManyField(related_name='route_address', through='address_app.RoureAddress', to='address_app.address', verbose_name='адреса'),
        ),
    ]
