# Generated by Django 5.1 on 2024-08-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0007_alter_beneficiar_options_remove_address_route_sheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routesheet',
            name='map',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='карта'),
        ),
    ]
