# Generated by Django 5.1 on 2024-09-02 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0009_rename_roureaddress_routeaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routesheet',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='route_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='address_app.routesheet', verbose_name='маршрутный лист'),
        ),
        migrations.AddField(
            model_name='routesheet',
            name='number',
            field=models.IntegerField(default=0, unique=True, verbose_name='номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_location', to='address_app.location', verbose_name='локация'),
        ),
        migrations.AlterField(
            model_name='beneficiar',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiar', to='address_app.address', verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='location',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='куратор'),
        ),
        migrations.AlterField(
            model_name='location',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ссылка'),
        ),
        migrations.DeleteModel(
            name='RouteAddress',
        ),
    ]
