# Generated by Django 5.1 on 2024-09-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0010_remove_routesheet_address_address_route_sheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routesheet',
            name='number',
            field=models.IntegerField(verbose_name='номер'),
        ),
    ]
