# Generated by Django 5.1 on 2024-09-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0011_alter_routesheet_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routesheet',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='номер'),
        ),
    ]
