# Generated by Django 5.1 on 2024-09-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0012_alter_routesheet_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routesheet',
            name='number',
        ),
        migrations.AddField(
            model_name='routesheet',
            name='name',
            field=models.CharField(default='first', max_length=500, unique=True, verbose_name='название'),
            preserve_default=False,
        ),
    ]
