# Generated by Django 5.1 on 2024-09-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0013_remove_routesheet_number_routesheet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='media_files',
            field=models.FileField(blank=True, null=True, upload_to='location_files', verbose_name='файлы'),
        ),
    ]
