# Generated by Django 5.1 on 2024-09-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0013_routesheet_user'),
        ('address_app', '0014_location_media_files'),
    ]

    operations = [
    ]
