# Generated by Django 5.1 on 2024-10-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0017_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiar',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='location',
            name='codename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='код локации'),
        ),
    ]
