# Generated by Django 5.1 on 2024-10-08 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0018_beneficiar_category_location_codename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='codename',
        ),
    ]
