# Generated by Django 5.1 on 2024-10-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0019_remove_location_codename'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiar',
            name='presence',
            field=models.CharField(choices=[('да', 'да'), ('в отъезде', 'в отъезде'), ('архив', 'архив')], default='да', max_length=15, verbose_name='присутствие'),
        ),
    ]
