# Generated by Django 5.1 on 2024-10-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0020_beneficiar_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiar',
            name='photo_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='просмотр фото'),
        ),
    ]
