# Generated by Django 5.1 on 2024-11-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0021_beneficiar_photo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiar',
            name='second_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='дополнительный телефон'),
        ),
    ]
