# Generated by Django 5.1 on 2024-11-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0022_remove_routesheet_user_routeassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiar',
            name='second_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='дополнительный телефон'),
        ),
    ]
