# Generated by Django 5.1 on 2025-01-13 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0027_alter_location_curator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiar',
            name='category',
        ),
    ]
