# Generated by Django 5.1 on 2025-03-02 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0028_remove_beneficiar_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='dinners',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='обедов'),
        ),
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='routeassignment',
            name='route_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='address_app.routesheet', verbose_name='маршрут'),
        ),
    ]
