# Generated by Django 5.1 on 2025-03-02 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0029_address_dinners_address_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='route_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='address_app.routesheet', verbose_name='маршрут'),
        ),
    ]
