# Generated by Django 5.1 on 2025-03-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0029_alter_routeassignment_route_sheet'),
        ('address_app', '0030_alter_address_route_sheet'),
    ]

    operations = [
    ]
