"""
Django settings for dariedu project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from datetime import timedelta
import logging

from django.conf import settings

from import_export.formats.base_formats import XLSX, XLS
from dotenv import load_dotenv, find_dotenv
from pathlib import Path
from .unfold_config import UNFOLD_CONFIG

load_dotenv(find_dotenv())
# logging.getLogger('django.utils.timezone').setLevel(logging.ERROR)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') or False

ALLOWED_HOSTS = [
    'localhost',
    '0.0.0.0',
    '127.0.0.1',
] + os.getenv('ALLOWED_HOSTS', '').split()

CURRENT_HOST = os.getenv('CURRENT_HOST')

BACKUP_DIR = os.path.join(BASE_DIR, 'backups/')

SITE_ID = 1
# Application definition

INSTALLED_APPS = [
    'unfold',
    "unfold.contrib.filters",
    "unfold.contrib.import_export",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',

    # apps
    'user_app.apps.UserAppConfig',
    'address_app',
    'task_app.apps.TaskAppConfig',
    'promo_app.apps.PromoAppConfig',
    'feedback_app.apps.FeedbackAppConfig',
    'stories_app',
    'notifications_app',
    'statistics_app',

    'django.contrib.postgres',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'drf_spectacular',
    'import_export',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_celery_beat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
    'dariedu.middleware.ErrorHandlerMiddleware',
    'dariedu.middleware.RequestResponseLoggingMiddleware',
    'dariedu.middleware.SecurityLoggingMiddleware',
]

ROOT_URLCONF = 'dariedu.urls'

CORS_ALLOWED_ORIGINS = [] + os.getenv('CORS_ALLOWED_ORIGINS', '').split()

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ["*"]
CORS_ALLOW_HEADERS = ["*"]

CSRF_TRUSTED_ORIGINS = [] + os.getenv('CSRF_TRUSTED_ORIGINS', '').split()

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dariedu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'ATOMIC_REQUESTS': True
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTH_USER_MODEL = 'user_app.User'


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'

LANGUAGES = [
    ('ru', 'русский'),
    ('en-us', 'english')
]

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = '/usr/src/app/staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_DIR = '/usr/src/app/media'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'media'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

UNFOLD = UNFOLD_CONFIG

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FileUploadParser',
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'DARIEDU API',
    'DESCRIPTION': 'This is a dariedu official API documentation',
    'VERSION': '1.0.0',
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'SERVE_INCLUDE_SCHEMA': False,
    "SWAGGER_UI_SETTINGS": {
            "filter": True,
    },
    "COMPONENT_SPLIT_REQUEST": True
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ALGORITHM": "HS256",
    "SIGNING_KEY": settings.SECRET_KEY,  # TODO add here another key
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
}

IMPORT_EXPORT_FORMATS = [XLSX, XLS]

CELERY_BROKER_URL = 'redis://redis:6379'
CELERY_RESULT_BACKEND = 'redis://redis:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'
CELERY_BEAT_MAX_INTERVAL = 1


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL')

# settings.py

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://redis:6379',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

FIRST_ROW_VALUES_CACHE_KEY = 'first_row_values'
FIRST_ROW_VALUES_CACHE_KEY_2 = 'first_row_values_2'
FIRST_ROW_VALUES_CACHE_KEY_3 = 'first_row_values_3'
FIRST_ROW_VALUES_CACHE_KEY_4 = 'first_row_values_4'

CACHE_STATS_WEEK_KEY = 'cache_stats_week'
CACHE_STATS_MONTH_KEY = 'cache_stats_month'
CACHE_STATS_YEAR_KEY = 'cache_stats_year'
CACHE_STATS_QUERYSET_KEY = 'cache_stats_queryset'
CACHE_STATS_ALL_KEY = 'cache_stats_all'

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'detailed': {
#             'format': '[{levelname}] {asctime} {module} {message}',
#             'style': '{',
#         },
#     },
#     'handlers': {
#         'console': {
#             'level': 'WARNING',
#             'class': 'logging.StreamHandler',
#             'formatter': 'detailed'
#         },
#     },
#     'loggers': {
#         'django.request': {
#             'handlers': ['console'],
#             'level': 'WARNING',
#             'propagate': False,
#         },
#     }
# }


LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process} {threadName} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '{levelname} {asctime} {module} {filename} {funcName} '
                      '{pathname} {lineno} {process} {thread} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'level': logging.INFO,
        },
        'django_request': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'django_request.log'),
            'formatter': 'detailed',
            'level': logging.WARNING,
        },
        'django_db': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'django_db.log'),
            'formatter': 'detailed',
            'level': logging.WARNING,
        },
        'django_server': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'django_server.log'),
            'formatter': 'detailed',
            'level': logging.WARNING,
        },
        'django_security': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'django_security.log'),
            'formatter': 'detailed',
            'level': logging.WARNING,
        },
        'google_photo': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'google_photo.log'),
            'formatter': 'detailed',
            'level': logging.WARNING,
        },
        'google_sheet': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'google_sheet.log'),
            'formatter': 'detailed',
            'level': logging.WARNING,
        },
        'celery_logs': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'celery_logs.log'),
            'formatter': 'detailed',
            'level': logging.DEBUG,
        },
        'celery_beat_log': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'celery_beat.log'),
            'formatter': 'detailed',
            'level': logging.DEBUG,
        },
    },
    'loggers': {
        'api.request': {
            'handlers': ['console', 'django_request'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.db.backends.schema': {
            'handlers': ['django_db'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'django_server'],
            'level': 'INFO',
            'propagate': True,
        },
        'middleware.security': {
            'handlers': ['console', 'django_security'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'google.photos': {
            'handlers': ['console', 'google_photo'],
            'level': 'INFO',
            'propagate': False,
        },
        'google.sheets': {
            'handlers': ['console', 'google_sheet'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery_log': {
            'handlers': ['console', 'celery_logs'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery_log.beat': {
            'handlers': ['console', 'celery_beat_log'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# logger.error(f'Ошибка в классе {self.__class__.__name__}: {str(e)}', exc_info=True)

# 'user': {
        #     'handlers': ['console', 'user_file'],
        #     'level': logging.DEBUG,
        #     'propagate': False,
        # },
        # 'task': {
        #     'handlers': ['console', 'task_file'],
        #     'level': logging.DEBUG,
        #     'propagate': False,
        # },
        # 'stories': {
        #     'handlers': ['console', 'stories_file'],
        #     'level': logging.DEBUG,
        #     'propagate': False,
        # },
        # 'statistics': {
        #     'handlers': ['console', 'statistics_file'],
        #     'level': logging.DEBUG,
        #     'propagate': False,
        # },
        # 'promo': {
        #     'handlers': ['console', 'promo_file'],
        #     'level': logging.DEBUG,
        #     'propagate': False,
        # },
        # 'notifications': {
        #     'handlers': ['console', 'notifications_file'],
        #     'level': logging.DEBUG,
        #     'propagate': False,
        # },
        # 'feedback': {
        #     'handlers': ['console', 'feedback_file'],
        #     'level': logging.DEBUG,
        #     'propagate': False,
        # },
        # 'address': {
        #     'handlers': ['console', 'address_file'],
        #     'level': logging.DEBUG,
        #     'propagate': False,
        # },